### ISSUE TITLE
file copyright.h missing from release

### ISSUE THREAD

**Issue by VictorEijkhout** [NanoComp/harminv#10]
I made my best guess as to `autogen`, did a subsequent configure, and now `make` runs into a missing `copyright.h` file.

**Comment by stevengj** [comment]
You are downloading the wrong file: use https://github.com/NanoComp/harminv/releases/download/v1.4.1/harminv-1.4.1.tar.gz

**Comment by stevengj** [comment]
(Similar to NanoComp/meep#1813)
