### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/harminv#5]
Trying to install harminv on macOS Sierra (10.12.6).  Cloned harminv from GitHub.com...

    git clone https://github.com/stevengj/harminv
    cd ./harminv

sh autogens.sh runs to completion.
./configure runs to completion.
make stops with the following message,
make: *** No rule to make target `copyright.h', needed by `all'.  Stop.

A few days ago I installed harminv on another iMac, running macOS Sierra, from the tarball without incident.

**Comment by stevengj** [comment]
You need to run `./configure --enable-maintainer-mode` to build from git.  autogen.sh does this for you, so you didn't need to run `configure` manually.

**Comment by JohnWeiner** [comment]
OK…I just downloaded the tarball and did the usual sequence of configure, make, sudo make install; and it proceeded without incident.  I wasn’t aware of the autogen feature…live and learn.

John

**Comment by stevengj** [comment]
I've updated the [installation instructions](https://github.com/stevengj/harminv/blob/master/doc/installation.md) to make this clearer.
